[phases.setup]
aptPkgs = ["tesseract-ocr", "tesseract-ocr-ind", "poppler-utils"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "gunicorn main:app --workers 2 --threads 4 --timeout 120 --bind 0.0.0.0:$PORT"